name: Run Batch File

on:
  push:
    branches:
      - main

jobs:
  run_batch_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run batch file
      run: C:/wamp64/www/demo/ngrokCommand.bat
